# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asana < Formula
  desc "Command-line client for Asana"
  homepage "https://github.com/ghost-vk/asana"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ghost-vk/asana/releases/download/v0.1.0/asana_0.1.0_darwin_amd64.tar.gz"
      sha256 "c8a7b3830164debce093889381902ad82a487cfa4e26e3becd49c0acc4a369b6"

      define_method(:install) do
        bin.install "asana"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ghost-vk/asana/releases/download/v0.1.0/asana_0.1.0_darwin_arm64.tar.gz"
      sha256 "85d84f08de279a64db418e79786004bbdf5ebf65279556fecfc5a1ee12a57fad"

      define_method(:install) do
        bin.install "asana"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghost-vk/asana/releases/download/v0.1.0/asana_0.1.0_linux_amd64.tar.gz"
      sha256 "53587f6498f037deba616bbe11ad77b8b126480052fde03100fde409f3a46674"
      define_method(:install) do
        bin.install "asana"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghost-vk/asana/releases/download/v0.1.0/asana_0.1.0_linux_arm64.tar.gz"
      sha256 "a382ee84f17187e86300ab33a85cb17c9adcfbb679d8a03ac57df31f82a0b9a1"
      define_method(:install) do
        bin.install "asana"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/asana --version")
  end
end
