# This file was generated by GoReleaser. DO NOT EDIT.
cask "asana" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "41cac6ff56351c2743f8e404b745cb5edc59b0727d0c7e1bb2adf1f7bcafdd13"
      url "https://github.com/ghost-vk/asana/releases/download/v#{version}/asana_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "633f9288baabd18f67023056d1306d5ac660853a6c23627f76290bf66cf4674a"
      url "https://github.com/ghost-vk/asana/releases/download/v#{version}/asana_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6ada6e7bbc4f82e2abeeffc1442ef945f1ceafa4e1055893122fa63c0573bdd3"
      url "https://github.com/ghost-vk/asana/releases/download/v#{version}/asana_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "240202472b22ea50c66d0f38e571ce9face3fb5bbb414c9907af9857fea485a3"
      url "https://github.com/ghost-vk/asana/releases/download/v#{version}/asana_#{version}_linux_arm64.tar.gz"
    end
  end

  name "asana"
  desc "Command-line client for Asana"
  homepage "https://github.com/ghost-vk/asana"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "asana"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/asana"]
    end
  end

  # No zap stanza required

end
