# This file was generated by GoReleaser. DO NOT EDIT.
cask "asana" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "749c403e383e28595d0d4304a51ccb16049c3ed724d36e3c2bae264a0e89f88c"
      url "https://github.com/ghost-vk/asana/releases/download/v#{version}/asana_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4d0ac473211fd6f43e182a15df16b3c822f136024e7b600db12fef323c353e40"
      url "https://github.com/ghost-vk/asana/releases/download/v#{version}/asana_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5dbae66c105d591c530eb2637b03a618d519defcc8e385c45b1701a44182884f"
      url "https://github.com/ghost-vk/asana/releases/download/v#{version}/asana_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b67f5eb52b3001662aab083d666ba453f87ac706abc9ce96dd4758cfec8eb714"
      url "https://github.com/ghost-vk/asana/releases/download/v#{version}/asana_#{version}_linux_arm64.tar.gz"
    end
  end

  name "asana"
  desc "Command-line client for Asana"
  homepage "https://github.com/ghost-vk/asana"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "asana"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/asana"]
    end
  end

  # No zap stanza required

end
