# This file was generated by GoReleaser. DO NOT EDIT.
cask "asana" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "b9f1c2cf23886faa54552d42319c18e04f86de09b3ca7e16e072bd862e1b1204"
      url "https://github.com/ghost-vk/asana/releases/download/v#{version}/asana_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a11b94b4361cbdc7efa794e368d6517004abf7f5a75dbac329c979442428e1f8"
      url "https://github.com/ghost-vk/asana/releases/download/v#{version}/asana_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "83798b6a61c031e366d4e48454edea0dd85a70790c30500a304d09f17f03ffae"
      url "https://github.com/ghost-vk/asana/releases/download/v#{version}/asana_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6adf09f03ebe3211ea6f6a2b371a78397f36006002ea516f727a5f4b7013e779"
      url "https://github.com/ghost-vk/asana/releases/download/v#{version}/asana_#{version}_linux_amd64.tar.gz"
    end
  end

  name "asana"
  desc "Command-line client for Asana"
  homepage "https://github.com/ghost-vk/asana"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "asana"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/asana"]
    end
  end

  # No zap stanza required
end
